# Site settings
title: Chen Hui Jing
email: hjchen13@gmail.com
description: The online playground of a newbie web developer.
baseurl: ""
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: hj_chen
github_username:  hjchen

# Build settings
markdown: kramdown
